<?php
/**
 *  @author Klaas Eikelboom (CiviCooP) <klaas.eikelboom@civicoop.org>
 *  @date 2/21/19 4:00 PM
 *  @license AGPL-3.0
 */

/**
 * Implements hook_l10n_update_languages_alter().
 */
function domusmedica_splitactivities_menu() {
  $items = [];
  $items['domusmedica_splitactivities/csv'] =
    ['title' => 'Lijst van wachtdiensten',
    'description' => 'Wachtdiensten',
    'page callback' => '_domusmedica_splitactivities_csv',
    'access arguments' => ['wachtdienstcoordinator'],
    'type' => MENU_NORMAL_ITEM,
    ];
  return $items;
}

/**
 *
 */
function _domusmedica_splitactivities_csv() {
  drupal_add_http_header('Content-Type','text/csv; charset=utf-8');
  drupal_add_http_header('Content-Disposition','attachment; filename=verantwoording.csv');
  civicrm_initialize();
  $exporter = new SplitActivitiesExporter(drupal_get_query_parameters());
  $exporter->readFromCivi();
  print($exporter->format());
}
/**
 *
 */
function _domusmedica_splitactivities_link(){
  $params = drupal_get_query_parameters();
  $link = url('domusmedica_splitactivities/csv',['query'=>$params]);
  print "<a href='$link'>Download CSV</a>";
}

